language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: 86287344@qq.com
  skip_cleanup: true
  api_key:
    secure: K/xbTscU/J7uqaQ5f4qKrWCczxfF+iidpuCS9D3lnERLPO48XtFWuDDkSCKFb6131fafhLIcVF0PZpijUvwCIc4O1r7j0xErlGBWLiGD71tbMdq+KrR73KQUYpY9QkdAtBT+PZDBUA5RR4CCgNhCFibx73gaoHM4IioU3cXUxGaUxxCgNQdVqWgjy3QrgS5kFQ7zhhK5m4JvtG3EbFCEvxEHeGqU1unIqrPWwt1batXbBDzTek7c3yDv/aAhgK2mbo8e1xe0nnaZkIMOf0R5bpkxOVJ1/kj8QEvGkXcm/mBYqOX/euqZscvIyqBvYKiqL/qpp/+A90ctPnbIkpzwqkezWcgly8wRrIZQ83BeDV9zv5YhrTeTacD10D7vgeSRh8kWOYJgsYH6crm1w1rnqYrLZKY/v3IHCf/QAQd+zvzqr5IRxRlWqQt29WrXImMehRzyXosxOSk0uVbHGlgzuG3MpjtSW9vIj0R3I5HpYAR0V6JD4WDtEEKoYWkXQMiGPs4xLJfzxL9HjaUK8haLGsYTKoeVOiSTmeo6wBeZJVIKhs0WUd92Qt32gdoFvpiNx1K2P++k9LThQPGJpmaFwXovf+ZXs3iEL+nszC22w8qeW0jG8ceRuSM0pQ+INWXPjAyZKnCEIf2/W2PFacBtFU6p5DiScpCLSkPo83EJz/0=
