language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: 86287344@qq.com
  skip_cleanup: true
  api_key:
    secure: MEBNeTVVQqdQXu+0R+gBIenjHEkISsQuHO/wJ3qmzSjME5PhHD5u5DkET42Zl3nuNFG2Nrg7WjJ9w+voE7FvOdz77BHTy+dZ1PT6qEiYcW/WD8a4wPS3Gq3hwvj+kridsAml98cPOKu6lBttjUbkcVtHolcH2DFxjVUJwHSIugrkIjA5Rxi4AdP/e3IJRTLEZdv6KbCAtgwFdw/pZaZDJMVms6zqgzcnNFmS9ZD4Ll3Xd5Statwi7Jj2qeRX8svdSWx+GDTg4kcSnBW8tazajgLi2Giq4/mlvxNC7ZEhXEM/OpN0JEMoON4hoTJzW8PTB6CT2MJMdOcJctqn1fgOWMkWmuBKJVODDZfS6ejMykV0RiNFS/ud4KN5rEHTmjwvGwOmyIeZsJi/wFXNSSaFpP0K9t0ML4mefVMw9IJQkQUpI8WnucHJQ8aLqqMew1bxjcCVD2+StcEQnhV8m866kf3NgEh3OHql/cuY+MCBQV5ZlLfqgrYwsJsV+4Znv7aBf5EdG3gHOPUAJA8CMjMU2saSKgUkaSJNXCEyZpAAwrwJ34N3xJN1/px/OPd9FOfVLkSdBSPWWJqbOz0U8YGpDgNbn/EuiAcTx8FlgMsz2M7ClsmTAZJ2j+uMll79VFmMZ9HKkbRL6MAGPS+2dwC7IxiGPRMau15YzUkEBb1/7To=
